// <auto-generated />
namespace PruebaTecnicaBitnovo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class usuarioId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usuarioId));
        
        string IMigrationMetadata.Id
        {
            get { return "202104171142407_usuarioId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
